const express = require('express')
const router = express.Router()
const auth = require('../middlewares/auth')
const authorize = require('../middlewares/authorize')
const { createLogMiddleware, ADMIN_RULES } = require('../middlewares/logOperation')
const ah = require('../utils/asyncHandler')
const ctrl = require('../controllers/adminController')

router.use(auth, authorize('admin'))
// D23 自动审计：admin 全部写操作成功后落 operation_logs（只记 2xx；GET 由中间件跳过）
router.use(createLogMiddleware(ADMIN_RULES))

router.get('/posts/pending', ah(ctrl.getPendingPosts))
router.put('/posts/:id/approve', ah(ctrl.approvePost))
router.put('/posts/:id/reject', ah(ctrl.rejectPost))
router.get('/applications', ah(ctrl.getApplications))
router.put('/applications/:id/approve', ah(ctrl.approveApplication))
router.put('/applications/:id/reject', ah(ctrl.rejectApplication))
router.get('/reports', ah(ctrl.getReports))
router.put('/reports/:id/resolve', ah(ctrl.resolveReport))
router.get('/users', ah(ctrl.getUserList))
router.put('/users/:id/ban', ah(ctrl.toggleBan))
router.delete('/users/:id', ah(ctrl.deleteUser))
router.get('/announcements', ah(ctrl.getAnnouncements))
router.post('/announcements', ah(ctrl.createAnnouncement))
router.put('/announcements/:id', ah(ctrl.updateAnnouncement))
router.put('/announcements/:id/publish', ah(ctrl.publishAnnouncement))
router.put('/announcements/:id/archive', ah(ctrl.archiveAnnouncement))
router.delete('/announcements/:id', ah(ctrl.deleteAnnouncement))
router.get('/stats', ah(ctrl.getStats))
router.get('/games', ah(ctrl.getGames))
router.get('/logs', ah(ctrl.getLogs))
router.post('/notifications', ah(ctrl.sendNotification))

module.exports = router
