const H = require('./helpers')
const crypto = require('crypto')
const fs = require('fs/promises')
const video = require('../src/services/videoService')

module.exports = async () => {
  await H.test('独立测试库及所有文本表显式使用utf8mb4', async () => {
    const [[schema]] = await H.pool.execute('SELECT DEFAULT_CHARACTER_SET_NAME AS charset FROM information_schema.SCHEMATA WHERE SCHEMA_NAME=DATABASE()')
    H.assert.equal(schema.charset, 'utf8mb4')
    const [[tables]] = await H.pool.execute("SELECT COUNT(*) AS bad FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_COLLATION NOT LIKE 'utf8mb4%'")
    H.assert.equal(+tables.bad, 0)
  })
  await H.test('临时防重记录过期回收，不删除历史统计事实、汇总或通知', async () => {
    const visitor = 'a'.repeat(64), id = await H.mkPost(await H.mkUser('expiry_author'))
    await H.pool.execute('INSERT INTO analytics_view_sessions(post_id,visitor_key,last_counted_at) VALUES(?,?,DATE_SUB(NOW(),INTERVAL 2 DAY))', [id,visitor])
    await H.pool.execute("INSERT INTO analytics_daily_visitors(scope_type,scope_id,metric_date,visitor_key) VALUES('post',?,DATE_SUB(CURDATE(),INTERVAL 10 DAY),?)", [id,visitor])
    const result = await require('../src/services/analyticsMaintenance').cleanupTransientAnalytics()
    H.assert.ok(result.sessions >= 1 && result.visitors >= 1)
    const [[left]] = await H.pool.execute('SELECT COUNT(*) AS n FROM analytics_view_sessions WHERE post_id=?', [id])
    H.assert.equal(+left.n, 0)
  })
  await H.test('已完成视频及进行中的合并不能通过已知MD5跨账号复用', async () => {
    const owner = await H.mkUser('hash_owner', { role: 'creator' }), other = await H.mkUser('hash_other', { role: 'creator' })
    const token = id => H.makeToken(id, 'video-test', 'creator')
    const payload = crypto.randomBytes(256 * 1024), hash = crypto.createHash('md5').update(payload).digest('hex')
    for (const id of [owner, other]) H.created.dirs.push(H.urlToAbs(`/uploads/videos/tmp/${id}-${hash}`))
    await video.saveChunk(hash, 0, payload, owner)
    const pending = video.mergeChunks(hash, 1, 'test.mp4', owner)
    const otherMerge = video.mergeChunks(hash, 1, 'test.mp4', other)
    H.assert.notEqual(pending, otherMerge)
    await H.assert.rejects(otherMerge, error => error.statusCode === 404)
    const url = H.trackFile(await pending)
    await require('../src/services/assetService').registerUpload(owner, { url, type: 'video', hash })
    const grant = (await H.http('GET', '/users/me', { token: token(other) })).headers['x-media-grant']
    const read = () => fetch('http://127.0.0.1:3199' + url, { headers: { Cookie: 'sg_media=' + grant } })
    H.assert.equal((await read()).status, 404)
    const status = await H.http('POST', '/media/upload/video/status', { token: token(other), body: { hash } })
    H.assert.equal(status.status, 200)
    H.assert.ok(!status.data.data.url)
    H.assert.equal((await read()).status, 404)
    const ownStatus = await H.http('POST', '/media/upload/video/status', { token: token(owner), body: { hash } })
    H.assert.equal(ownStatus.data.data.url, url)
    await video.saveChunk(hash, 0, payload, other)
    H.assert.notEqual(H.trackFile(await video.mergeChunks(hash, 1, 'test.mp4', other)), url)
  })
  await H.test('旧版会话仅原所有者可恢复，分片落盘与合并交叠不会读取半片', async () => {
    const owner = await H.mkUser('legacy_video', { role: 'creator' }), other = await H.mkUser('legacy_other', { role: 'creator' })
    const payload = crypto.randomBytes(128 * 1024), hash = crypto.createHash('md5').update(payload).digest('hex')
    const legacy = H.urlToAbs(`/uploads/videos/tmp/${hash}`)
    H.created.dirs.push(legacy, H.urlToAbs(`/uploads/videos/tmp/${other}-${hash}`))
    await fs.mkdir(legacy, { recursive: true }); await fs.writeFile(legacy + '/__owner__', String(owner))
    const saving = video.saveChunk(hash, 0, payload, owner)
    const merging = video.mergeChunks(hash, 1, 'legacy.mp4', owner)
    await saving; H.trackFile(await merging)
    H.assert.deepEqual(await video.listUploadedChunks(hash, other, true), [])
    await H.assert.rejects(video.saveChunk(hash, 0, Buffer.alloc(5 * 1024 * 1024 + 1), owner), /5MB/)
  })
  await H.test('互动率使用同周期同范围读者交集，不读文章的互动不制造超过100%的结果', async () => {
    const owner = await H.mkUser('rate_author', { role: 'creator' }), reader = await H.mkUser('rate_reader'), actor = await H.mkUser('rate_actor')
    const token = id => H.makeToken(id, 'rate-test', id === owner ? 'creator' : 'user')
    const id = await H.mkPost(owner, { status: 'published' }), another = await H.mkPost(owner, { status: 'published' })
    H.assert.equal((await H.http('POST', `/posts/${id}/view`, { token: token(reader), body: { visitor_id: 'rate_visitor_123456789' } })).status, 200)
    for (const user of [reader, actor]) H.assert.equal((await H.http('POST', `/posts/${id}/like`, { token: token(user) })).status, 200)
    await H.http('POST', `/posts/${another}/like`, { token: token(reader) })
    const response = await H.http('GET', `/creator/stats?post_id=${id}&rank_by=engagement_rate`, { token: token(owner) })
    H.assert.equal(response.status, 200, response.data?.message)
    const data = response.data.data
    H.assert.equal(data.period.likes_added, 2); H.assert.equal(data.period.uv, 1)
    H.assert.equal(data.period.engaged_users, 1); H.assert.equal(data.period.engagement_rate, 100)
    H.assert.equal(data.top_posts[0].engagement_rate, 100)
    H.assert.equal(data.category_performance[0].engagement_rate, 100)
    const otherStats = (await H.http('GET', `/creator/stats?post_id=${another}`, { token: token(owner) })).data.data
    H.assert.equal(otherStats.period.engagement_rate, 0)
    H.assert.equal(otherStats.top_posts[0].engagement_rate, 0)
  })
}
