FROM nginx:alpine
COPY client/dist /usr/share/nginx/html
COPY nginx/nginx.prod-http.conf /etc/nginx/nginx.prod.template
COPY nginx/security-headers-http.conf /etc/nginx/security-headers.conf
COPY nginx/19-site-config.sh /docker-entrypoint.d/19-site-config.sh
RUN chmod +x /docker-entrypoint.d/19-site-config.sh && chmod -R o+rX /usr/share/nginx/html
