const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const crypto = require('node:crypto')
const root = path.resolve(__dirname,'../..')
const manifest = require(path.join(root,'.artifacts/article-illustrations-20261004/generated-manifest.json'))
const before = require(path.join(root,'.artifacts/article-illustrations-20261004/posts-before.json'))
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex')
for(const p of manifest.images) {
  const escapedUrl = p.url.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')
  const insertion = new RegExp(`<p><img src="${escapedUrl}"[^>]*\\/></p><p><em>[^<]+</em></p>`)
  const old = before.posts.find(r=>r.id===p.id)
  assert.equal(p.content.replace(insertion,''),old.content,'original text changed')
  assert.equal((p.content.match(/<img\b/gi)||[]).length,1)
  assert.equal(p.cover,old.cover);assert.deepEqual(p.expectedMedia,old.media)
  assert.equal(sha(fs.readFileSync(path.join(root,'assets/article-illustrations-20261004',p.file))),p.sha256)
  assert.equal(p.width,1200);assert.equal(p.height,675);assert.ok(p.bytes<=350*1024)
}
assert.equal(new Set(manifest.images.map(p=>p.sha256)).size,manifest.count)
console.log(JSON.stringify({validated:manifest.count,originalTextCoversMediaPreserved:true,uniqueImages:true,issues:[]}))
